### ISSUE TITLE
3D Technical Specification Group (TSG) charter

### ISSUE THREAD

**Issue by JulieWinchester** [IIIF/3d#1]
Taken from @azaroth42's https://github.com/IIIF/api/issues/1992

Requirement: Charter document laying out the nature, goals, and timelines of the 3D TSG. 

Rationale: Required to become a IIIF TSG. 

Status: [Current draft of charter](https://docs.google.com/document/d/13OysSJc3tNRUJUrNbo16_RYOTPRHJpOnHkROQZO6JwM/edit)

**Comment by hadro** [comment]
For the record, the charter was approved in December 2021 and is published here: https://iiif.io/community/groups/3d/tsg-charter/
