### ISSUE TITLE
Host a single "canonical" annotation JSON file

### ISSUE THREAD

**Issue by JulieWinchester** [IIIF/3d#23]
Acceptance criteria:
- Create a single complete stand-alone JSON file encoding demo annotations to be used by each demo

**Comment by gjcope** [comment]
Per 4/19 meeting - Will we include annotation tag offset in the proposed spec? Would that happen through magnitude of normal vector or in another way?

**Comment by JulieWinchester** [comment]
This example JSON is now hosted on IIIF 3D repo: https://github.com/IIIF/3d/blob/main/demo/json/label-annotation-issue-17.json

**Comment by edsilv** [comment]
That's the model-viewer demo updated to use the above annotation json format: https://codesandbox.io/s/model-viewer-annotations-demo-3k5tqo?file=/index.html
