### ISSUE TITLE
Modify viewer demos to use canonical JSON and viewer-specific translation snippet (make issue per viewer)

### ISSUE THREAD

**Issue by JulieWinchester** [IIIF/3d#25]
We need forks of code sandboxes for the individual demos in the [viewer demo documentation](https://github.com/IIIF/3d/blob/main/demo/VIEWER_JSON_DEMOS.md) modified to use our [common JSON label annotations](https://github.com/IIIF/3d/blob/main/demo/json/label-annotation-issue-17.json).

- [x] Aleph
- [x] Google Model Viewer
- [x] Sketchfab
- [x] Smithsonian Voyager
- [x] X3D

**Comment by gjcope** [comment]
Voyager demo fork is here: https://codesandbox.io/s/voyager-annotations-demo-forked-rqivl4?file=/index.html

Main adjustment was aligning attribute names.

**Comment by edsilv** [comment]
Sketchfab demo: https://codesandbox.io/s/sad-lena-b39r00?file=/src/index.js

**Comment by edsilv** [comment]
modelviewer annos pasted into sketchfab: 
![630F3894-53A5-4CCA-ABA8-F7151231C4F3](https://github.com/IIIF/3d/assets/1334393/d05a7c96-79a0-4f92-8f4b-16f3a0b5c4a1)

sketchfab annos pasted into modelviewer:
![6A89C632-7F9D-4A75-A65A-258EC8A1E481](https://github.com/IIIF/3d/assets/1334393/be27f62b-7776-4c18-9ce9-76a39f6c0d32)

@gjcope any chance you could add a text field under Voyager to copy/paste annotation json into/out of?

**Comment by JulieWinchester** [comment]
Aleph demo: https://codesandbox.io/s/aleph-annotation-demo-common-annotation-json-8rbos9

I also added a text field similar to what the Model Viewer demo uses to allow for interactive experimentation with annotation JSON.

**Comment by edsilv** [comment]
Tried copying/pasting annotations between the aleph and modelviewer demos and they appear in their correct locations.

**Comment by vincentmarchetti** [comment]
have modified the X3D viewer to read annotations from a local copy of the canonical json at https://github.com/IIIF/3d/blob/main/demo/json/label-annotation-issue-17.json at commit c353301

X3D demo is at 
https://codesandbox.io/p/github/vincentmarchetti/x3d-remote-annotation

**Comment by JulieWinchester** [comment]
This task and this project have been successfully completed, good work all! Thanks to everyone for all of the effort and great results.
