### ISSUE TITLE
incorrect placement of backgroundColor in draft manifest

### ISSUE THREAD

**Issue by vincentmarchetti** [IIIF/3d#45]
In the draft manifest showing example of a backgroundColor being defined on the Scene ( manifests/1_basic_model_in_scene/model_origin_bgcolor.json ) it looks like the json backgroundColor value is being defined as a property in the Manifest, not the Scene

If and when this is corrected, I suggest breaking the equality between the red and blue values, so set for example

"backgroundColor": "#FF00FE",

This will enable a unit test to detect if an implementation is rearranging the color values.

**Comment by glenrobson** [comment]
This is the Manifest: https://github.com/IIIF/3d/blob/eds/manifests/1_basic_model_in_scene/model_origin_bgcolor.json

TSG Group agrees backgroundColor should be moved to scene.
