### ISSUE TITLE
Analyze and describe requirements around annotation in a 3D environment

### ISSUE THREAD

**Issue by JulieWinchester** [IIIF/3d#5]
Taken from @azaroth42's IIIF/api#1992

Requirement: A document analyzing and describing the requirements around annotation precision in a 3d environment. For example, is a cube enough, or do the use cases require arbitrary volumes?

Rationale: Annotation is a core functionality of IIIF, and there aren't 3d annotation targeting specifications we can simply reference, thus knowing the requirements explicitly around annotation is very useful to set out in the right direction. This is needed for both comment annotations (look at this arm of the statue) and positioning models in the space (this statues goes here, that statue goes there).

Status: Unknown

**Comment by JulieWinchester** [comment]
As the TSG group has now been certified, this document should be linked in this story (if it was created) and the story can probably be closed as either completed or not planned?

**Comment by hadro** [comment]
@edsilv drafted this doc which was included as part of the materials reviewed by the TRC when they approved the TSG: https://docs.google.com/document/d/1ZhUyevjFEet8nefvYEZH1b4xuv9x0iHBaw7DRMD7sbg/edit
