### ISSUE TITLE
Analyze and describe requirements around intersection of 3D content and non-3D content in the same rendering environment

### ISSUE THREAD

**Issue by JulieWinchester** [IIIF/3d#6]
Taken from @azaroth42's IIIF/api#1992

Proposed Requirement: A document analyzing and describing the requirements around the intersection of 3d and other formats in the same canvas / space. For example, what should happen when you include audio, video or image content along with a 3d model in a 3d space.

Rationale: The existing functionality of the Presentation API should be available, in the same way that adding AV material in v3 can be done in the same environment as the content available in v2.

Status: Unknown

**Comment by JulieWinchester** [comment]
This was discussed during the pre-TSG working group meeting on October 5th, with the general sentiment being that this document be short (1-2 pages). Content should briefly address the above topics and help to indicate the scope that would hope to be addressed by future work.

**Comment by JulieWinchester** [comment]
As the TSG group has now been certified, this document should be linked in this story (if it was created) and the story can probably be closed as either completed or not planned?

**Comment by hadro** [comment]
FWIW, the doc being referred to is here:
https://docs.google.com/document/d/1J_L-klpYbp24TvQMTQory4p43APbp92c90xj4Y7vG9k/edit

and was included among the TSG approval materials reviewed by the TRC

I'll leave it to others to comment about closing this up or other linking, etc
