### ISSUE TITLE
Analyze and describe the requirements around intersections with Authentication and Search APIs for 3D content

### ISSUE THREAD

**Issue by JulieWinchester** [IIIF/3d#7]
Proposed Requirement: A document analyzing and describing the requirements around the intersections with Authentication and Search. Especially pertinent, given the current TSGs for those topics.

Rationale: All of the IIIF APIs should work together when needed. If there are authentication or search requirements that are specific to 3d, now is the time to work on them, not after the current TSGs have concluded.

Status: Unknown

**Comment by JulieWinchester** [comment]
This was discussed during the pre-TSG working group meeting on October 5th, with the general sentiment being that this document be short (1-2 pages). Content should briefly address the above topics and help to indicate the scope that would hope to be addressed by future work. It may be the case that 3D content doesn't require much (if anything?) from the Authentication and Search APIs, this needs further discussion.

**Comment by JulieWinchester** [comment]
As the TSG group has now been certified, this document should be linked in this story (if it was created) and the story can probably be closed as either completed or not planned?

**Comment by hadro** [comment]
Good point -- the doc being referred to is here, and was included among the TSG approval materials reviewed by the TRC: https://docs.google.com/document/d/1h-gie-e-qI4JEWtIk62OCZ8le6nQ2-YYAXsxFbq0t3s/edit

I'll leave it to others to comment about closing this up or other linking, etc.
